### ISSUE TITLE
Plugin Can't Enable

### ISSUE THREAD

**Issue by Hikari16665** [Shershnyaga007/BetterCallFishing#5]
### Error Log
```
[04:01:35] [Server thread/INFO]: [BetterCallFishing] Enabling BetterCallFishing v2.0.3
[04:01:35] [Server thread/ERROR]: Error occurred while enabling BetterCallFishing v2.0.3 (Is it up to date?)
java.lang.NullPointerException: null
	at java.base/java.io.Reader.<init>(Reader.java:168) ~[?:?]
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:108) ~[?:?]
	at BetterCallFishing-2.0.3-b45.jar/me.sherhsnyaga.bettercallfishing.BetterCallFishing.loadLang(BetterCallFishing.java:84) ~[BetterCallFishing-2.0.3-b45.jar:?]
	at BetterCallFishing-2.0.3-b45.jar/me.sherhsnyaga.bettercallfishing.BetterCallFishing.reloadConfig(BetterCallFishing.java:66) ~[BetterCallFishing-2.0.3-b45.jar:?]
	at BetterCallFishing-2.0.3-b45.jar/me.sherhsnyaga.bettercallfishing.BetterCallFishing.onEnable(BetterCallFishing.java:47) ~[BetterCallFishing-2.0.3-b45.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
### Reproduction steps
 I made a Chinese translation for BetterCallFishing,
```
# This translation was created by Hikari
#  If you want to translate the plugin into your own language, please let me know about this:
#  https://www.spigotmc.org/members/shershnyaga_.1502182/
# Multilingualism is cool!
reload-message: '<green>[BetterCallFishing] 重新加载已完成!'
update-detect-message:
  - '<blue>----------------'
  - '<green>BetterCallFishing 已发现更新!'
  - '<green>最新版本: <blue>%new_version%'
  - '<green>当前版本: <blue>%current_version%'
  - '%version_info%'
  - '<blue>----------------'
updated-message: '<green>[BetterCallFishing] 更新已准备完毕! 请重新启动服务器.'
old-barrel-name: '<gold>破旧的木桶'
```
And I changed the lang-file setting and restarted the server.
The plugin displays the above error message, and disabled itself.

**Comment by Shershnyaga007** [comment]
Thanks for the report! I will fix this bug in the next experimental release.
